name: STM32 HIL CI

on:
  push:
    branches:
      - main

jobs:
  hil-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build firmware with Keil
        run: |
          & "C:\Users\asmad\AppData\Local\Keil_v5\UV4\UV4.exe" -b "firmware\Embedded_Test_Bench\MDK-ARM\Embedded_Test_Bench.uvprojx"

      - name: Flash STM32 firmware
        run: |
          & "C:\Program Files\STMicroelectronics\STM32Cube\STM32CubeProgrammer\bin\STM32_Programmer_CLI.exe" `
          -c port=SWD `
          -w "firmware\Embedded_Test_Bench\MDK-ARM\Embedded_Test_Bench\Embedded_Test_Bench.hex" `
          -v `
          -rst

      - name: Run STM32 HIL tests
        run: pytest --html=reports/test_report.html --self-contained-html --junitxml=reports/results.xml

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hil-test-reports
          path: |
            reports/test_report.html
            reports/results.xml

      - name: Upload validated firmware
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: validated-firmware
          path: |
            firmware/Embedded_Test_Bench/MDK-ARM/Embedded_Test_Bench/Embedded_Test_Bench.hex
            firmware/Embedded_Test_Bench/MDK-ARM/Embedded_Test_Bench/Embedded_Test_Bench.axf